### ISSUE TITLE
Dashboard Creation - Initial charts

### ISSUE THREAD

**Issue by MattyJP** [MattyJP/IMAT2214-Summative-Assessment-2#6]
Created two dashboard functions using hard-coded dates for the following functions:
-Sales by day (shows the whole week)
-Weekly sales by product type

**Comment by CLucas96** [comment]
Initial charts created, Charts do Load but no data is being pulled into the charts. will fix ASAP

**Comment by MattyJP** [comment]
The count is returned as zero due to the dates being checked in the wrong format.
Rather than changing all the hard-coded date values by hand, it's probably worth reformatting them during the loop by using an array to split.
Edit: The format to convert to is yyyy-mm-dd

**Comment by CLucas96** [comment]
Will fix issues soon, Line Chart will also be changed to a Pie Chart. Line chart was used to test wether the second graph was showing. As Pie Charts do not show when blank

**Comment by CLucas96** [comment]
Hard coded dates are being stored in the salesCount Dictionary, dates do show on the graphs but i'm currently facing issues with the data flowing from the .mdf files into the graphs.
