### ISSUE TITLE
Dashboard Creation - Third chart functionality

### ISSUE THREAD

**Issue by MattyJP** [MattyJP/IMAT2214-Summative-Assessment-2#8]
*MUST BE DISCUSSED BY ALL PRIOR TO CREATION AND ASSIGNMENT TO ROLE*
Creation of a third chart function on the dashboard to complement the other two charts. Must be useful, relevant and helpful to a business (has to be justified in the demo).

**Comment by MattyJP** [comment]
Just a few ideas:
- Line graph displaying profits over ALL weeks by department (with different lines per department, probably also toggleable via comboBox or other control).
- Sales by region (Suitable for pie chart/bar chart)

**Comment by CLucas96** [comment]
Ideas: 
- Pie Chart/Line chart indicating popular products within season with the addition with a combo box for different categories. 
- Histogram of monthly sales. (Combo Box for different months).
